version: 2.1

jobs:
  build_and_test:
    docker:
      - image: cimg/openjdk:17.0  
    environment:
      DEPLOY_PATH: /tmp/deploy
    steps:
      - checkout

      - run:
          name: Build (Maven package)
          command: mvn clean package -DskipTests

      - run:
          name: Run Tests
          command: mvn test

      - store_test_results:
          path: target/surefire-reports/

      - run:
          name: Checkstyle analysis
          command: mvn checkstyle:checkstyle

      - store_artifacts:
          path: target/site/checkstyle.html
          destination: checkstyle-report

      - run:
          name: Deploy Local (Simulación)
          command: |
            rm -rf $DEPLOY_PATH
            mkdir -p $DEPLOY_PATH
            cp target/*.jar $DEPLOY_PATH/deploy_integrador_calidad.jar

workflows:
  build_test_deploy:
    jobs:
      - build_and_test